// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const activeUsersPerClientThisWeek = `-- name: ActiveUsersPerClientThisWeek :many
SELECT
  metadata->>'client_id' AS client_id,
  COUNT(DISTINCT user_id) AS active_users
FROM audit_logs
WHERE action = 'login'
  AND COALESCE((metadata->>'success')::boolean, false) = true
  AND created_at >= DATE_TRUNC('week', CURRENT_DATE)
GROUP BY client_id
`

type ActiveUsersPerClientThisWeekRow struct {
	ClientID    interface{} `json:"client_id"`
	ActiveUsers int64       `json:"active_users"`
}

func (q *Queries) ActiveUsersPerClientThisWeek(ctx context.Context) ([]ActiveUsersPerClientThisWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, activeUsersPerClientThisWeek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActiveUsersPerClientThisWeekRow{}
	for rows.Next() {
		var i ActiveUsersPerClientThisWeekRow
		if err := rows.Scan(&i.ClientID, &i.ActiveUsers); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const activeUsersPerClientToday = `-- name: ActiveUsersPerClientToday :many
SELECT
  metadata->>'client_id' AS client_id,
  COUNT(DISTINCT user_id) AS active_users
FROM audit_logs
WHERE action = 'login'
  AND (metadata->>'success')::boolean = true
  AND DATE(created_at) = CURRENT_DATE
GROUP BY client_id
`

type ActiveUsersPerClientTodayRow struct {
	ClientID    interface{} `json:"client_id"`
	ActiveUsers int64       `json:"active_users"`
}

func (q *Queries) ActiveUsersPerClientToday(ctx context.Context) ([]ActiveUsersPerClientTodayRow, error) {
	rows, err := q.db.QueryContext(ctx, activeUsersPerClientToday)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActiveUsersPerClientTodayRow{}
	for rows.Next() {
		var i ActiveUsersPerClientTodayRow
		if err := rows.Scan(&i.ClientID, &i.ActiveUsers); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const activeUsersThisWeek = `-- name: ActiveUsersThisWeek :one
SELECT COUNT(DISTINCT user_id)
FROM audit_logs
WHERE action = 'login'
  AND (metadata->>'success')::boolean = true
  AND DATE(created_at) >= DATE_TRUNC('week', CURRENT_DATE)
`

func (q *Queries) ActiveUsersThisWeek(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, activeUsersThisWeek)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const activeUsersToday = `-- name: ActiveUsersToday :one
SELECT COUNT(DISTINCT user_id)
FROM audit_logs
WHERE action = 'login'
  AND (metadata->>'success')::boolean = true
  AND DATE(created_at) = CURRENT_DATE
`

func (q *Queries) ActiveUsersToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, activeUsersToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const approximateActiveSessions = `-- name: ApproximateActiveSessions :one
SELECT COUNT(DISTINCT user_id)
FROM audit_logs
WHERE action = 'login'
  AND (metadata->>'success')::boolean = true
  AND created_at >= NOW() - INTERVAL '15 minutes'
`

func (q *Queries) ApproximateActiveSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, approximateActiveSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const auditMetricsOverview = `-- name: AuditMetricsOverview :one
SELECT
  COUNT(*)::bigint AS total_events,
  SUM(CASE WHEN metadata->>'success' = 'false' THEN 1 ELSE 0 END)::bigint AS total_failures,
  SUM(CASE WHEN action = 'login' AND metadata->>'success' = 'false' THEN 1 ELSE 0 END)::bigint AS failed_logins,
  SUM(CASE WHEN action = 'login' AND metadata->>'success' = 'true' THEN 1 ELSE 0 END)::bigint AS successful_logins
FROM audit_logs
WHERE
  created_at >= $1
  AND created_at <  $2
`

type AuditMetricsOverviewParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
}

type AuditMetricsOverviewRow struct {
	TotalEvents      int64 `json:"total_events"`
	TotalFailures    int64 `json:"total_failures"`
	FailedLogins     int64 `json:"failed_logins"`
	SuccessfulLogins int64 `json:"successful_logins"`
}

func (q *Queries) AuditMetricsOverview(ctx context.Context, arg AuditMetricsOverviewParams) (AuditMetricsOverviewRow, error) {
	row := q.db.QueryRowContext(ctx, auditMetricsOverview, arg.StartTime, arg.EndTime)
	var i AuditMetricsOverviewRow
	err := row.Scan(
		&i.TotalEvents,
		&i.TotalFailures,
		&i.FailedLogins,
		&i.SuccessfulLogins,
	)
	return i, err
}

const clientUsageForUserInRange = `-- name: ClientUsageForUserInRange :many
SELECT
  metadata->>'client_id' AS client_id,
  COUNT(*) AS login_count
FROM audit_logs
WHERE action = 'login'
  AND COALESCE((metadata->>'success')::boolean, false) = true
  AND user_id = $1::uuid
  AND created_at BETWEEN $2 AND $3
GROUP BY client_id
`

type ClientUsageForUserInRangeParams struct {
	UserID    uuid.UUID    `json:"user_id"`
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
}

type ClientUsageForUserInRangeRow struct {
	ClientID   interface{} `json:"client_id"`
	LoginCount int64       `json:"login_count"`
}

func (q *Queries) ClientUsageForUserInRange(ctx context.Context, arg ClientUsageForUserInRangeParams) ([]ClientUsageForUserInRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, clientUsageForUserInRange, arg.UserID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClientUsageForUserInRangeRow{}
	for rows.Next() {
		var i ClientUsageForUserInRangeRow
		if err := rows.Scan(&i.ClientID, &i.LoginCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActiveUsers = `-- name: CountActiveUsers :one
SELECT COUNT(DISTINCT user_id)
FROM audit_logs
WHERE action = 'login'
  AND created_at >= NOW() - INTERVAL '30 days'
`

func (q *Queries) CountActiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveUsersInRange = `-- name: CountActiveUsersInRange :one
SELECT COUNT(DISTINCT user_id)
FROM audit_logs
WHERE action = 'login'
  AND (metadata->>'success')::boolean = true
  AND created_at BETWEEN $1 AND $2
`

type CountActiveUsersInRangeParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
}

func (q *Queries) CountActiveUsersInRange(ctx context.Context, arg CountActiveUsersInRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveUsersInRange, arg.StartTime, arg.EndTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFailedLogins = `-- name: CountFailedLogins :one
SELECT COUNT(*)
FROM audit_logs
WHERE action = 'login'
  AND (metadata->>'success')::boolean = false
`

func (q *Queries) CountFailedLogins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFailedLogins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFailedLoginsInRange = `-- name: CountFailedLoginsInRange :one
SELECT COUNT(*)
FROM audit_logs
WHERE action = 'login'
  AND (metadata->>'success')::boolean = false
  AND created_at BETWEEN $1 AND $2
`

type CountFailedLoginsInRangeParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
}

func (q *Queries) CountFailedLoginsInRange(ctx context.Context, arg CountFailedLoginsInRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFailedLoginsInRange, arg.StartTime, arg.EndTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPasswordResetsInRange = `-- name: CountPasswordResetsInRange :one
SELECT COUNT(*)
FROM audit_logs
WHERE action = 'password_reset'
  AND created_at BETWEEN $1 AND $2
`

type CountPasswordResetsInRangeParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
}

func (q *Queries) CountPasswordResetsInRange(ctx context.Context, arg CountPasswordResetsInRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPasswordResetsInRange, arg.StartTime, arg.EndTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :exec
	-- AuditLogs
	-- =====================================================

INSERT INTO audit_logs (
    user_id, action, metadata
) VALUES (
    $1, $2, $3
)
`

type CreateAuditLogParams struct {
	UserID   uuid.NullUUID         `json:"user_id"`
	Action   string                `json:"action"`
	Metadata pqtype.NullRawMessage `json:"metadata"`
}

// =====================================================
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, createAuditLog, arg.UserID, arg.Action, arg.Metadata)
	return err
}

const exportAuditLogs = `-- name: ExportAuditLogs :many
SELECT
  a.id,
  a.created_at,
  a.user_id,
  COALESCE(u.username, 'System') AS username,
  a.action,
  a.metadata
FROM audit_logs a
LEFT JOIN users u ON u.id = a.user_id
WHERE
  a.created_at >= $1
  AND a.created_at <  $2

  AND ($3 IS NULL OR a.action = $3)
  AND ($4 IS NULL OR a.user_id = $4)
  AND ($5 IS NULL OR a.metadata->>'client_id' = $5)
  AND ($6 IS NULL OR a.metadata->>'ip' = $6)
  AND ($7 IS NULL OR a.metadata->>'success' = $7)

ORDER BY a.created_at ASC, a.id ASC
`

type ExportAuditLogsParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
	Action    interface{}  `json:"action"`
	UserID    interface{}  `json:"user_id"`
	ClientID  interface{}  `json:"client_id"`
	Ip        interface{}  `json:"ip"`
	Success   interface{}  `json:"success"`
}

type ExportAuditLogsRow struct {
	ID        uuid.UUID             `json:"id"`
	CreatedAt sql.NullTime          `json:"created_at"`
	UserID    uuid.NullUUID         `json:"user_id"`
	Username  string                `json:"username"`
	Action    string                `json:"action"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) ExportAuditLogs(ctx context.Context, arg ExportAuditLogsParams) ([]ExportAuditLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, exportAuditLogs,
		arg.StartTime,
		arg.EndTime,
		arg.Action,
		arg.UserID,
		arg.ClientID,
		arg.Ip,
		arg.Success,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportAuditLogsRow{}
	for rows.Next() {
		var i ExportAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.Username,
			&i.Action,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failedLoginsByDay = `-- name: FailedLoginsByDay :many
SELECT
  date_trunc('day', created_at) AS day,
  COUNT(*)::bigint AS count
FROM audit_logs
WHERE
  created_at >= $1 AND created_at < $2
  AND action = 'login'
  AND metadata->>'success' = 'false'
GROUP BY 1
ORDER BY 1 ASC
`

type FailedLoginsByDayParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
}

type FailedLoginsByDayRow struct {
	Day   int64 `json:"day"`
	Count int64 `json:"count"`
}

func (q *Queries) FailedLoginsByDay(ctx context.Context, arg FailedLoginsByDayParams) ([]FailedLoginsByDayRow, error) {
	rows, err := q.db.QueryContext(ctx, failedLoginsByDay, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FailedLoginsByDayRow{}
	for rows.Next() {
		var i FailedLoginsByDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failedLoginsByUserInRange = `-- name: FailedLoginsByUserInRange :many
SELECT user_id, COUNT(*) AS failure_count
FROM audit_logs
WHERE action = 'login'
  AND COALESCE((metadata->>'success')::boolean, false) = false
  AND created_at BETWEEN $1 AND $2
GROUP BY user_id
`

type FailedLoginsByUserInRangeParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
}

type FailedLoginsByUserInRangeRow struct {
	UserID       uuid.NullUUID `json:"user_id"`
	FailureCount int64         `json:"failure_count"`
}

func (q *Queries) FailedLoginsByUserInRange(ctx context.Context, arg FailedLoginsByUserInRangeParams) ([]FailedLoginsByUserInRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, failedLoginsByUserInRange, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FailedLoginsByUserInRangeRow{}
	for rows.Next() {
		var i FailedLoginsByUserInRangeRow
		if err := rows.Scan(&i.UserID, &i.FailureCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const firstLoginForUser = `-- name: FirstLoginForUser :one
SELECT created_at
FROM audit_logs
WHERE user_id = $1::uuid
  AND action = 'login'
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) FirstLoginForUser(ctx context.Context, userID uuid.UUID) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, firstLoginForUser, userID)
	var created_at sql.NullTime
	err := row.Scan(&created_at)
	return created_at, err
}

const getAuditLog = `-- name: GetAuditLog :one
SELECT
  a.id,
  a.created_at,
  a.user_id,
  COALESCE(u.username, 'System') AS username,
  a.action,
  a.metadata
FROM audit_logs a
LEFT JOIN users u ON u.id = a.user_id
WHERE a.id = $1
`

type GetAuditLogRow struct {
	ID        uuid.UUID             `json:"id"`
	CreatedAt sql.NullTime          `json:"created_at"`
	UserID    uuid.NullUUID         `json:"user_id"`
	Username  string                `json:"username"`
	Action    string                `json:"action"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) GetAuditLog(ctx context.Context, id uuid.UUID) (GetAuditLogRow, error) {
	row := q.db.QueryRowContext(ctx, getAuditLog, id)
	var i GetAuditLogRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.Username,
		&i.Action,
		&i.Metadata,
	)
	return i, err
}

const inactiveUsersSince = `-- name: InactiveUsersSince :many
SELECT u.id, u.username, u.first_name, u.last_name, u.email, u.enabled, u.roles, u.created_at, u.updated_at, u.last_login_at
FROM users u
LEFT JOIN LATERAL (
    SELECT created_at
    FROM audit_logs a
    WHERE a.user_id = u.id
      AND a.action = 'login'
      AND (a.metadata->>'success')::boolean = true
    ORDER BY created_at DESC
    LIMIT 1
) last_login ON TRUE
WHERE last_login.created_at IS NULL
   OR last_login.created_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) InactiveUsersSince(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, inactiveUsersSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Enabled,
			pq.Array(&i.Roles),
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lastLoginForAllUsers = `-- name: LastLoginForAllUsers :many
SELECT u.id AS user_id,
       MAX(a.created_at) AS last_login_at
FROM users u
LEFT JOIN audit_logs a
       ON a.user_id = u.id
      AND a.action = 'login'
      AND (a.metadata->>'success')::boolean = true
GROUP BY u.id
`

type LastLoginForAllUsersRow struct {
	UserID      uuid.UUID   `json:"user_id"`
	LastLoginAt interface{} `json:"last_login_at"`
}

func (q *Queries) LastLoginForAllUsers(ctx context.Context) ([]LastLoginForAllUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, lastLoginForAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LastLoginForAllUsersRow{}
	for rows.Next() {
		var i LastLoginForAllUsersRow
		if err := rows.Scan(&i.UserID, &i.LastLoginAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lastLoginForUser = `-- name: LastLoginForUser :one
SELECT created_at AS last_login_at
FROM audit_logs
WHERE action = 'login'
  AND (metadata->>'success')::boolean = true
  AND user_id = $1::uuid
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) LastLoginForUser(ctx context.Context, userID uuid.UUID) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, lastLoginForUser, userID)
	var last_login_at sql.NullTime
	err := row.Scan(&last_login_at)
	return last_login_at, err
}

const listAuditActions = `-- name: ListAuditActions :many
SELECT DISTINCT action
FROM audit_logs
ORDER BY action ASC
`

func (q *Queries) ListAuditActions(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAuditActions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var action string
		if err := rows.Scan(&action); err != nil {
			return nil, err
		}
		items = append(items, action)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT
  a.id,
  a.created_at,
  a.user_id,
  COALESCE(u.username, 'System') AS username,
  a.action,
  a.metadata
FROM audit_logs a
LEFT JOIN users u ON u.id = a.user_id
WHERE
  a.created_at >= $1::timestamptz
  AND a.created_at <  $2::timestamptz

  AND ($3::text IS NULL OR a.action = $3::text)
  AND ($4::uuid IS NULL OR a.user_id = $4::uuid)

  AND (
    $5::text IS NULL
    OR a.metadata->>'client_id' = $5::text
  )

  AND (
    $6::text IS NULL
    OR a.metadata->>'ip' = $6::text
  )

  AND (
    $7::text IS NULL
    OR a.metadata->>'success' = $7::text
  )

  AND (
    $8::timestamptz IS NULL
    OR $9::uuid IS NULL
    OR (a.created_at, a.id)
       < ($8::timestamptz,
          $9::uuid)
  )
ORDER BY a.created_at DESC, a.id DESC
LIMIT $10::int
`

type ListAuditLogsParams struct {
	StartTime       time.Time      `json:"start_time"`
	EndTime         time.Time      `json:"end_time"`
	Action          sql.NullString `json:"action"`
	UserID          uuid.NullUUID  `json:"user_id"`
	ClientID        sql.NullString `json:"client_id"`
	Ip              sql.NullString `json:"ip"`
	Success         sql.NullString `json:"success"`
	CursorCreatedAt sql.NullTime   `json:"cursor_created_at"`
	CursorID        uuid.NullUUID  `json:"cursor_id"`
	RowLimit        int32          `json:"row_limit"`
}

type ListAuditLogsRow struct {
	ID        uuid.UUID             `json:"id"`
	CreatedAt sql.NullTime          `json:"created_at"`
	UserID    uuid.NullUUID         `json:"user_id"`
	Username  string                `json:"username"`
	Action    string                `json:"action"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs,
		arg.StartTime,
		arg.EndTime,
		arg.Action,
		arg.UserID,
		arg.ClientID,
		arg.Ip,
		arg.Success,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.Username,
			&i.Action,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loginCountForClientInRange = `-- name: LoginCountForClientInRange :one
SELECT COUNT(*)
FROM audit_logs
WHERE action = 'login'
  AND (metadata->>'success')::boolean = true
  AND metadata->>'client_id' = $1::text
  AND created_at BETWEEN $2 AND $3
`

type LoginCountForClientInRangeParams struct {
	ClientID  string       `json:"client_id"`
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
}

func (q *Queries) LoginCountForClientInRange(ctx context.Context, arg LoginCountForClientInRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, loginCountForClientInRange, arg.ClientID, arg.StartTime, arg.EndTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const loginCountPerUserInRange = `-- name: LoginCountPerUserInRange :many
SELECT
  user_id,
  COUNT(*) AS login_count
FROM audit_logs
WHERE action = 'login'
  AND (metadata->>'success')::boolean = true
  AND created_at BETWEEN $1 AND $2
GROUP BY user_id
`

type LoginCountPerUserInRangeParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
}

type LoginCountPerUserInRangeRow struct {
	UserID     uuid.NullUUID `json:"user_id"`
	LoginCount int64         `json:"login_count"`
}

func (q *Queries) LoginCountPerUserInRange(ctx context.Context, arg LoginCountPerUserInRangeParams) ([]LoginCountPerUserInRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, loginCountPerUserInRange, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginCountPerUserInRangeRow{}
	for rows.Next() {
		var i LoginCountPerUserInRangeRow
		if err := rows.Scan(&i.UserID, &i.LoginCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loginSuccessFailureInRange = `-- name: LoginSuccessFailureInRange :one
SELECT
  COUNT(*) FILTER (WHERE (metadata->>'success')::boolean = true) AS success_count,
  COUNT(*) FILTER (WHERE (metadata->>'success')::boolean = false) AS failure_count
FROM audit_logs
WHERE action = 'login'
  AND created_at BETWEEN $1 AND $2
`

type LoginSuccessFailureInRangeParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
}

type LoginSuccessFailureInRangeRow struct {
	SuccessCount int64 `json:"success_count"`
	FailureCount int64 `json:"failure_count"`
}

func (q *Queries) LoginSuccessFailureInRange(ctx context.Context, arg LoginSuccessFailureInRangeParams) (LoginSuccessFailureInRangeRow, error) {
	row := q.db.QueryRowContext(ctx, loginSuccessFailureInRange, arg.StartTime, arg.EndTime)
	var i LoginSuccessFailureInRangeRow
	err := row.Scan(&i.SuccessCount, &i.FailureCount)
	return i, err
}

const loginTrend = `-- name: LoginTrend :many
SELECT 
  DATE(created_at) AS day,
  COUNT(*) AS total
FROM audit_logs
WHERE action = 'login'
  AND created_at >= NOW() - INTERVAL '30 days'
GROUP BY day
ORDER BY day
`

type LoginTrendRow struct {
	Day   time.Time `json:"day"`
	Total int64     `json:"total"`
}

func (q *Queries) LoginTrend(ctx context.Context) ([]LoginTrendRow, error) {
	rows, err := q.db.QueryContext(ctx, loginTrend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginTrendRow{}
	for rows.Next() {
		var i LoginTrendRow
		if err := rows.Scan(&i.Day, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loginTrendByDay = `-- name: LoginTrendByDay :many
SELECT
  DATE(created_at) AS day,
  COUNT(*) FILTER (WHERE (metadata->>'success')::boolean = true) AS success_count,
  COUNT(*) FILTER (WHERE (metadata->>'success')::boolean = false) AS failure_count
FROM audit_logs
WHERE action = 'login'
  AND created_at BETWEEN $1 AND $2
GROUP BY day
ORDER BY day
`

type LoginTrendByDayParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
}

type LoginTrendByDayRow struct {
	Day          time.Time `json:"day"`
	SuccessCount int64     `json:"success_count"`
	FailureCount int64     `json:"failure_count"`
}

func (q *Queries) LoginTrendByDay(ctx context.Context, arg LoginTrendByDayParams) ([]LoginTrendByDayRow, error) {
	rows, err := q.db.QueryContext(ctx, loginTrendByDay, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginTrendByDayRow{}
	for rows.Next() {
		var i LoginTrendByDayRow
		if err := rows.Scan(&i.Day, &i.SuccessCount, &i.FailureCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mostAccessedClients = `-- name: MostAccessedClients :many
SELECT
  metadata->>'client_id' AS client_id,
  COUNT(*) AS login_count
FROM audit_logs
WHERE action = 'login'
  AND (metadata->>'success')::boolean = true
  AND created_at BETWEEN $1 AND $2
GROUP BY client_id
ORDER BY login_count DESC
LIMIT $3
`

type MostAccessedClientsParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
	RowLimit  int32        `json:"row_limit"`
}

type MostAccessedClientsRow struct {
	ClientID   interface{} `json:"client_id"`
	LoginCount int64       `json:"login_count"`
}

func (q *Queries) MostAccessedClients(ctx context.Context, arg MostAccessedClientsParams) ([]MostAccessedClientsRow, error) {
	rows, err := q.db.QueryContext(ctx, mostAccessedClients, arg.StartTime, arg.EndTime, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MostAccessedClientsRow{}
	for rows.Next() {
		var i MostAccessedClientsRow
		if err := rows.Scan(&i.ClientID, &i.LoginCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mostActiveClients = `-- name: MostActiveClients :many
SELECT 
  metadata->>'client_id' AS client_id,
  COUNT(*) AS hits
FROM audit_logs
WHERE action = 'login'
GROUP BY client_id
ORDER BY hits DESC
`

type MostActiveClientsRow struct {
	ClientID interface{} `json:"client_id"`
	Hits     int64       `json:"hits"`
}

func (q *Queries) MostActiveClients(ctx context.Context) ([]MostActiveClientsRow, error) {
	rows, err := q.db.QueryContext(ctx, mostActiveClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MostActiveClientsRow{}
	for rows.Next() {
		var i MostActiveClientsRow
		if err := rows.Scan(&i.ClientID, &i.Hits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suspiciousLoginsInRange = `-- name: SuspiciousLoginsInRange :many
SELECT
  id,
  user_id,
  metadata->>'ip' AS ip,
  metadata->>'country' AS country,
  metadata->>'city' AS city,
  created_at
FROM audit_logs
WHERE action = 'login'
  AND (metadata->>'success')::boolean = true
  AND created_at BETWEEN $1 AND $2
  AND metadata->>'country' IS NOT NULL
  AND metadata->>'country' <> $3::text
`

type SuspiciousLoginsInRangeParams struct {
	StartTime   sql.NullTime `json:"start_time"`
	EndTime     sql.NullTime `json:"end_time"`
	HomeCountry string       `json:"home_country"`
}

type SuspiciousLoginsInRangeRow struct {
	ID        uuid.UUID     `json:"id"`
	UserID    uuid.NullUUID `json:"user_id"`
	Ip        interface{}   `json:"ip"`
	Country   interface{}   `json:"country"`
	City      interface{}   `json:"city"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

func (q *Queries) SuspiciousLoginsInRange(ctx context.Context, arg SuspiciousLoginsInRangeParams) ([]SuspiciousLoginsInRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, suspiciousLoginsInRange, arg.StartTime, arg.EndTime, arg.HomeCountry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SuspiciousLoginsInRangeRow{}
	for rows.Next() {
		var i SuspiciousLoginsInRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Ip,
			&i.Country,
			&i.City,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topFailureIPs = `-- name: TopFailureIPs :many
SELECT
  COALESCE(metadata->>'ip', 'unknown') AS ip,
  COUNT(*)::bigint AS count
FROM audit_logs
WHERE
  created_at >= $1
  AND created_at <  $2
  AND metadata->>'success' = 'false'
GROUP BY ip
ORDER BY count DESC
LIMIT $3
`

type TopFailureIPsParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
	RowLimit  int32        `json:"row_limit"`
}

type TopFailureIPsRow struct {
	Ip    interface{} `json:"ip"`
	Count int64       `json:"count"`
}

func (q *Queries) TopFailureIPs(ctx context.Context, arg TopFailureIPsParams) ([]TopFailureIPsRow, error) {
	rows, err := q.db.QueryContext(ctx, topFailureIPs, arg.StartTime, arg.EndTime, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopFailureIPsRow{}
	for rows.Next() {
		var i TopFailureIPsRow
		if err := rows.Scan(&i.Ip, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topTenantsByLogins = `-- name: TopTenantsByLogins :many
SELECT
  metadata->>'tenant_id' AS tenant_id,
  COUNT(*) AS login_count
FROM audit_logs
WHERE action = 'login'
  AND (metadata->>'success')::boolean = true
  AND created_at BETWEEN $1 AND $2
GROUP BY tenant_id
ORDER BY login_count DESC
LIMIT $3
`

type TopTenantsByLoginsParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
	RowLimit  int32        `json:"row_limit"`
}

type TopTenantsByLoginsRow struct {
	TenantID   interface{} `json:"tenant_id"`
	LoginCount int64       `json:"login_count"`
}

func (q *Queries) TopTenantsByLogins(ctx context.Context, arg TopTenantsByLoginsParams) ([]TopTenantsByLoginsRow, error) {
	rows, err := q.db.QueryContext(ctx, topTenantsByLogins, arg.StartTime, arg.EndTime, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopTenantsByLoginsRow{}
	for rows.Next() {
		var i TopTenantsByLoginsRow
		if err := rows.Scan(&i.TenantID, &i.LoginCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalLoginsInRange = `-- name: TotalLoginsInRange :one
SELECT COUNT(*)
FROM audit_logs
WHERE action = 'login'
  AND created_at BETWEEN $1 AND $2
`

type TotalLoginsInRangeParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
}

func (q *Queries) TotalLoginsInRange(ctx context.Context, arg TotalLoginsInRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, totalLoginsInRange, arg.StartTime, arg.EndTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const userAgentStatsInRange = `-- name: UserAgentStatsInRange :many
SELECT
  metadata->>'user_agent' AS user_agent,
  COUNT(*) AS count
FROM audit_logs
WHERE action = 'login'
  AND created_at BETWEEN $1 AND $2
GROUP BY user_agent
ORDER BY count DESC
`

type UserAgentStatsInRangeParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
}

type UserAgentStatsInRangeRow struct {
	UserAgent interface{} `json:"user_agent"`
	Count     int64       `json:"count"`
}

func (q *Queries) UserAgentStatsInRange(ctx context.Context, arg UserAgentStatsInRangeParams) ([]UserAgentStatsInRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, userAgentStatsInRange, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserAgentStatsInRangeRow{}
	for rows.Next() {
		var i UserAgentStatsInRangeRow
		if err := rows.Scan(&i.UserAgent, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
