// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createClient = `-- name: CreateClient :exec
INSERT INTO client (
    id, client_id, name, description, base_url, icon, public_client, enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreateClientParams struct {
	ID           uuid.UUID      `json:"id"`
	ClientID     string         `json:"client_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	BaseUrl      sql.NullString `json:"base_url"`
	Icon         sql.NullString `json:"icon"`
	PublicClient sql.NullBool   `json:"public_client"`
	Enabled      sql.NullBool   `json:"enabled"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) error {
	_, err := q.db.ExecContext(ctx, createClient,
		arg.ID,
		arg.ClientID,
		arg.Name,
		arg.Description,
		arg.BaseUrl,
		arg.Icon,
		arg.PublicClient,
		arg.Enabled,
	)
	return err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM client
WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteClient, id)
	return err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, client_id, name, description, base_url, icon, public_client, enabled, created_at, updated_at
FROM client
WHERE id = $1
`

func (q *Queries) GetClientByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.BaseUrl,
		&i.Icon,
		&i.PublicClient,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, client_id, name, description, base_url, icon, public_client, enabled, created_at, updated_at
FROM client
ORDER BY name ASC
`

func (q *Queries) ListClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Description,
			&i.BaseUrl,
			&i.Icon,
			&i.PublicClient,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :exec
UPDATE client
SET
    client_id = $2,
    name = $3,
    description = $4,
    base_url = $5,
    icon = $6,
    public_client = $7,
    enabled = $8
WHERE id = $1
`

type UpdateClientParams struct {
	ID           uuid.UUID      `json:"id"`
	ClientID     string         `json:"client_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	BaseUrl      sql.NullString `json:"base_url"`
	Icon         sql.NullString `json:"icon"`
	PublicClient sql.NullBool   `json:"public_client"`
	Enabled      sql.NullBool   `json:"enabled"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) error {
	_, err := q.db.ExecContext(ctx, updateClient,
		arg.ID,
		arg.ClientID,
		arg.Name,
		arg.Description,
		arg.BaseUrl,
		arg.Icon,
		arg.PublicClient,
		arg.Enabled,
	)
	return err
}
