// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countClients = `-- name: CountClients :one
SELECT COUNT(*) 
FROM client
`

func (q *Queries) CountClients(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClients)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDisabledClients = `-- name: CountDisabledClients :one
SELECT COUNT(*)
FROM client
WHERE enabled = false
`

func (q *Queries) CountDisabledClients(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDisabledClients)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnabledClients = `-- name: CountEnabledClients :one
SELECT COUNT(*)
FROM client
WHERE enabled = true
`

func (q *Queries) CountEnabledClients(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnabledClients)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNewClientsThisWeek = `-- name: CountNewClientsThisWeek :one
SELECT COUNT(*)
FROM client
WHERE created_at >= DATE_TRUNC('week', CURRENT_DATE)
`

func (q *Queries) CountNewClientsThisWeek(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNewClientsThisWeek)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNewClientsToday = `-- name: CountNewClientsToday :one
SELECT COUNT(*)
FROM client
WHERE DATE(created_at) = CURRENT_DATE
`

func (q *Queries) CountNewClientsToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNewClientsToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClient = `-- name: CreateClient :exec

INSERT INTO client (
    id,
    client_id,
    name,
    description,
    base_url,
    icon,
    public_client,
    enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,$8
)
ON CONFLICT (client_id) DO NOTHING
RETURNING id
`

type CreateClientParams struct {
	ID           uuid.UUID      `json:"id"`
	ClientID     string         `json:"client_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	BaseUrl      sql.NullString `json:"base_url"`
	Icon         sql.NullString `json:"icon"`
	PublicClient sql.NullBool   `json:"public_client"`
	Enabled      sql.NullBool   `json:"enabled"`
}

// =====================================================
// Clients
// =====================================================
func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) error {
	_, err := q.db.ExecContext(ctx, createClient,
		arg.ID,
		arg.ClientID,
		arg.Name,
		arg.Description,
		arg.BaseUrl,
		arg.Icon,
		arg.PublicClient,
		arg.Enabled,
	)
	return err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM client
WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteClient, id)
	return err
}

const getClientByClientID = `-- name: GetClientByClientID :one
SELECT id, client_id, name, description, base_url, icon, public_client, enabled, created_at, updated_at
FROM client
WHERE client_id = $1
`

func (q *Queries) GetClientByClientID(ctx context.Context, clientID string) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByClientID, clientID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.BaseUrl,
		&i.Icon,
		&i.PublicClient,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, client_id, name, description, base_url, icon, public_client, enabled, created_at, updated_at
FROM client
WHERE id = $1
`

func (q *Queries) GetClientByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.BaseUrl,
		&i.Icon,
		&i.PublicClient,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, client_id, name, description, base_url, icon, public_client, enabled, created_at, updated_at
FROM client
ORDER BY name ASC
`

func (q *Queries) ListClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Description,
			&i.BaseUrl,
			&i.Icon,
			&i.PublicClient,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientsPaged = `-- name: ListClientsPaged :many
SELECT id, client_id, name, description, base_url, icon, public_client, enabled, created_at, updated_at
FROM client
ORDER BY name ASC
LIMIT $2 OFFSET $1
`

type ListClientsPagedParams struct {
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

func (q *Queries) ListClientsPaged(ctx context.Context, arg ListClientsPagedParams) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listClientsPaged, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Description,
			&i.BaseUrl,
			&i.Icon,
			&i.PublicClient,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledClients = `-- name: ListEnabledClients :many
SELECT id, client_id, name, description, base_url, icon, public_client, enabled, created_at, updated_at
FROM client
WHERE enabled = true
ORDER BY name ASC
`

func (q *Queries) ListEnabledClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Description,
			&i.BaseUrl,
			&i.Icon,
			&i.PublicClient,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newClientsInRange = `-- name: NewClientsInRange :many
SELECT
    id,
    client_id,
    name,
    description,
    base_url,
    icon,
    public_client,
    enabled,
    created_at,
    updated_at
FROM client
WHERE created_at BETWEEN $1 AND $2
ORDER BY created_at DESC
`

type NewClientsInRangeParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
}

func (q *Queries) NewClientsInRange(ctx context.Context, arg NewClientsInRangeParams) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, newClientsInRange, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Description,
			&i.BaseUrl,
			&i.Icon,
			&i.PublicClient,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentlyCreatedClients = `-- name: RecentlyCreatedClients :many
SELECT
    id,
    client_id,
    name,
    description,
    base_url,
    icon,
    public_client,
    enabled,
    created_at,
    updated_at
FROM client
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) RecentlyCreatedClients(ctx context.Context, rowLimit int32) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, recentlyCreatedClients, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Description,
			&i.BaseUrl,
			&i.Icon,
			&i.PublicClient,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchClients = `-- name: SearchClients :many
SELECT id, client_id, name, description, base_url, icon, public_client, enabled, created_at, updated_at
FROM client
WHERE 
    (
        name ILIKE '%' || $1 || '%'
        OR client_id ILIKE '%' || $1 || '%'
        OR description ILIKE '%' || $1 || '%'
    )
ORDER BY name ASC
`

func (q *Queries) SearchClients(ctx context.Context, query sql.NullString) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, searchClients, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Description,
			&i.BaseUrl,
			&i.Icon,
			&i.PublicClient,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :exec
UPDATE client
SET
    client_id = $2,
    name = $3,
    description = $4,
    base_url = $5,
    icon = $6,
    public_client = $7,
    enabled = $8,
    updated_at = NOW()
WHERE id = $1
`

type UpdateClientParams struct {
	ID           uuid.UUID      `json:"id"`
	ClientID     string         `json:"client_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	BaseUrl      sql.NullString `json:"base_url"`
	Icon         sql.NullString `json:"icon"`
	PublicClient sql.NullBool   `json:"public_client"`
	Enabled      sql.NullBool   `json:"enabled"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) error {
	_, err := q.db.ExecContext(ctx, updateClient,
		arg.ID,
		arg.ClientID,
		arg.Name,
		arg.Description,
		arg.BaseUrl,
		arg.Icon,
		arg.PublicClient,
		arg.Enabled,
	)
	return err
}

const upsertClient = `-- name: UpsertClient :exec
INSERT INTO client (
    id,
    client_id,
    name,
    description,
    base_url,
    icon,
    public_client,
    enabled
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (client_id)
DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    base_url = EXCLUDED.base_url,
    icon = EXCLUDED.icon,
    public_client = EXCLUDED.public_client,
    enabled = EXCLUDED.enabled,
    updated_at = NOW()
`

type UpsertClientParams struct {
	ID           uuid.UUID      `json:"id"`
	ClientID     string         `json:"client_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	BaseUrl      sql.NullString `json:"base_url"`
	Icon         sql.NullString `json:"icon"`
	PublicClient sql.NullBool   `json:"public_client"`
	Enabled      sql.NullBool   `json:"enabled"`
}

func (q *Queries) UpsertClient(ctx context.Context, arg UpsertClientParams) error {
	_, err := q.db.ExecContext(ctx, upsertClient,
		arg.ID,
		arg.ClientID,
		arg.Name,
		arg.Description,
		arg.BaseUrl,
		arg.Icon,
		arg.PublicClient,
		arg.Enabled,
	)
	return err
}
