// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: import_jobs.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createImportJob = `-- name: CreateImportJob :exec

INSERT INTO import_jobs (
  id, filename, status, total_rows, valid_rows, success_count, failure_count, created_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreateImportJobParams struct {
	ID           uuid.UUID       `json:"id"`
	Filename     string          `json:"filename"`
	Status       ImportJobStatus `json:"status"`
	TotalRows    int32           `json:"total_rows"`
	ValidRows    int32           `json:"valid_rows"`
	SuccessCount int32           `json:"success_count"`
	FailureCount int32           `json:"failure_count"`
	CreatedBy    string          `json:"created_by"`
}

// =====================================================
// Import Jobs
// =====================================================
func (q *Queries) CreateImportJob(ctx context.Context, arg CreateImportJobParams) error {
	_, err := q.db.ExecContext(ctx, createImportJob,
		arg.ID,
		arg.Filename,
		arg.Status,
		arg.TotalRows,
		arg.ValidRows,
		arg.SuccessCount,
		arg.FailureCount,
		arg.CreatedBy,
	)
	return err
}

const getImportJob = `-- name: GetImportJob :one
SELECT id, filename, status, total_rows, valid_rows, success_count, failure_count, created_by, created_at, updated_at
FROM import_jobs
WHERE id = $1
`

func (q *Queries) GetImportJob(ctx context.Context, id uuid.UUID) (ImportJob, error) {
	row := q.db.QueryRowContext(ctx, getImportJob, id)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Status,
		&i.TotalRows,
		&i.ValidRows,
		&i.SuccessCount,
		&i.FailureCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertImportJobItem = `-- name: InsertImportJobItem :exec
INSERT INTO import_job_items (
  id, job_id, row_number, username, email, first_name, last_name, roles, enabled, client_ids, status, error_msg
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
`

type InsertImportJobItemParams struct {
	ID        uuid.UUID      `json:"id"`
	JobID     uuid.UUID      `json:"job_id"`
	RowNumber int32          `json:"row_number"`
	Username  sql.NullString `json:"username"`
	Email     sql.NullString `json:"email"`
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	Roles     []string       `json:"roles"`
	Enabled   sql.NullBool   `json:"enabled"`
	ClientIds sql.NullString `json:"client_ids"`
	Status    string         `json:"status"`
	ErrorMsg  sql.NullString `json:"error_msg"`
}

func (q *Queries) InsertImportJobItem(ctx context.Context, arg InsertImportJobItemParams) error {
	_, err := q.db.ExecContext(ctx, insertImportJobItem,
		arg.ID,
		arg.JobID,
		arg.RowNumber,
		arg.Username,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		pq.Array(arg.Roles),
		arg.Enabled,
		arg.ClientIds,
		arg.Status,
		arg.ErrorMsg,
	)
	return err
}

const listImportJobFailedItems = `-- name: ListImportJobFailedItems :many
SELECT id, job_id, row_number, username, email, first_name, last_name, roles, enabled, email_sent, email_sent_at, client_ids, status, error_msg, created_at
FROM import_job_items
WHERE job_id = $1 AND status IN ('failed')
ORDER BY row_number ASC
`

func (q *Queries) ListImportJobFailedItems(ctx context.Context, jobID uuid.UUID) ([]ImportJobItem, error) {
	rows, err := q.db.QueryContext(ctx, listImportJobFailedItems, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportJobItem{}
	for rows.Next() {
		var i ImportJobItem
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.RowNumber,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			pq.Array(&i.Roles),
			&i.Enabled,
			&i.EmailSent,
			&i.EmailSentAt,
			&i.ClientIds,
			&i.Status,
			&i.ErrorMsg,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportJobItems = `-- name: ListImportJobItems :many
SELECT id, job_id, row_number, username, email, first_name, last_name, roles, enabled, email_sent, email_sent_at, client_ids, status, error_msg, created_at
FROM import_job_items
WHERE job_id = $1
ORDER BY row_number ASC
`

func (q *Queries) ListImportJobItems(ctx context.Context, jobID uuid.UUID) ([]ImportJobItem, error) {
	rows, err := q.db.QueryContext(ctx, listImportJobItems, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportJobItem{}
	for rows.Next() {
		var i ImportJobItem
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.RowNumber,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			pq.Array(&i.Roles),
			&i.Enabled,
			&i.EmailSent,
			&i.EmailSentAt,
			&i.ClientIds,
			&i.Status,
			&i.ErrorMsg,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImportJobCounts = `-- name: UpdateImportJobCounts :exec
UPDATE import_jobs
SET
  total_rows = $2,
  valid_rows = $3,
  success_count = $4,
  failure_count = $5,
  updated_at = now()
WHERE id = $1
`

type UpdateImportJobCountsParams struct {
	ID           uuid.UUID `json:"id"`
	TotalRows    int32     `json:"total_rows"`
	ValidRows    int32     `json:"valid_rows"`
	SuccessCount int32     `json:"success_count"`
	FailureCount int32     `json:"failure_count"`
}

func (q *Queries) UpdateImportJobCounts(ctx context.Context, arg UpdateImportJobCountsParams) error {
	_, err := q.db.ExecContext(ctx, updateImportJobCounts,
		arg.ID,
		arg.TotalRows,
		arg.ValidRows,
		arg.SuccessCount,
		arg.FailureCount,
	)
	return err
}

const updateImportJobItemStatus = `-- name: UpdateImportJobItemStatus :exec
UPDATE import_job_items
SET status = $2, error_msg = $3
WHERE id = $1
`

type UpdateImportJobItemStatusParams struct {
	ID       uuid.UUID      `json:"id"`
	Status   string         `json:"status"`
	ErrorMsg sql.NullString `json:"error_msg"`
}

func (q *Queries) UpdateImportJobItemStatus(ctx context.Context, arg UpdateImportJobItemStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateImportJobItemStatus, arg.ID, arg.Status, arg.ErrorMsg)
	return err
}

const updateImportJobStatus = `-- name: UpdateImportJobStatus :exec
UPDATE import_jobs
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateImportJobStatusParams struct {
	ID     uuid.UUID       `json:"id"`
	Status ImportJobStatus `json:"status"`
}

func (q *Queries) UpdateImportJobStatus(ctx context.Context, arg UpdateImportJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateImportJobStatus, arg.ID, arg.Status)
	return err
}
