// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditLog struct {
	ID        int64                 `json:"id"`
	UserID    uuid.NullUUID         `json:"user_id"`
	Action    string                `json:"action"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
	CreatedAt sql.NullTime          `json:"created_at"`
}

type Client struct {
	ID           uuid.UUID      `json:"id"`
	ClientID     string         `json:"client_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	BaseUrl      sql.NullString `json:"base_url"`
	Icon         sql.NullString `json:"icon"`
	PublicClient sql.NullBool   `json:"public_client"`
	Enabled      sql.NullBool   `json:"enabled"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type ClientSecret struct {
	ID         uuid.UUID    `json:"id"`
	ClientID   uuid.UUID    `json:"client_id"`
	SecretHash string       `json:"secret_hash"`
	CreatedAt  sql.NullTime `json:"created_at"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
}

type RevokedToken struct {
	ID        int64        `json:"id"`
	TokenHash string       `json:"token_hash"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

type Role struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	UserAgent    sql.NullString `json:"user_agent"`
	IpAddress    sql.NullString `json:"ip_address"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	ExpiresAt    time.Time      `json:"expires_at"`
}

type User struct {
	ID          uuid.UUID      `json:"id"`
	Username    string         `json:"username"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	Email       string         `json:"email"`
	Enabled     sql.NullBool   `json:"enabled"`
	Role        string         `json:"role"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	LastLoginAt sql.NullTime   `json:"last_login_at"`
}

type UserClientAccess struct {
	UserID    uuid.UUID    `json:"user_id"`
	ClientID  uuid.UUID    `json:"client_id"`
	GrantedAt sql.NullTime `json:"granted_at"`
}

type UserRole struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}
