// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countNotifications = `-- name: CountNotifications :one
SELECT COUNT(*)::bigint
FROM notifications
WHERE target_role = $1
`

func (q *Queries) CountNotifications(ctx context.Context, targetRole string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotifications, targetRole)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*)::bigint
FROM notifications
WHERE
  target_role = $1
  AND read = FALSE
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, targetRole string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, targetRole)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createNotification = `-- name: CreateNotification :one

INSERT INTO notifications (
  type,
  title,
  message,
  severity,
  target_role,
  metadata
)
VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, type, title, message, severity, target_role, metadata, read, created_at
`

type CreateNotificationParams struct {
	Type       string                `json:"type"`
	Title      string                `json:"title"`
	Message    string                `json:"message"`
	Severity   sql.NullString        `json:"severity"`
	TargetRole string                `json:"target_role"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
}

// =====================================================
// Notifications
// =====================================================
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.Type,
		arg.Title,
		arg.Message,
		arg.Severity,
		arg.TargetRole,
		arg.Metadata,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.Severity,
		&i.TargetRole,
		&i.Metadata,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotificationByID = `-- name: DeleteNotificationByID :exec
DELETE FROM notifications
WHERE id = $1
`

func (q *Queries) DeleteNotificationByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationByID, id)
	return err
}

const deleteOldNotifications = `-- name: DeleteOldNotifications :exec
DELETE FROM notifications
WHERE created_at < NOW() - INTERVAL '90 days'
`

func (q *Queries) DeleteOldNotifications(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOldNotifications)
	return err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, type, title, message, severity, target_role, metadata, read, created_at
FROM notifications
WHERE id = $1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.Severity,
		&i.TargetRole,
		&i.Metadata,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, type, title, message, severity, target_role, metadata, read, created_at
FROM notifications
WHERE
  target_role = $1
  AND (
    $4::boolean IS NULL
    OR read = NOT $4
  )
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	TargetRole string       `json:"target_role"`
	Limit      int32        `json:"limit"`
	Offset     int32        `json:"offset"`
	Unread     sql.NullBool `json:"unread"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications,
		arg.TargetRole,
		arg.Limit,
		arg.Offset,
		arg.Unread,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.Severity,
			&i.TargetRole,
			&i.Metadata,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByCursor = `-- name: ListNotificationsByCursor :many
SELECT id, type, title, message, severity, target_role, metadata, read, created_at
FROM notifications
WHERE
  target_role = $1
  AND (
    $3::timestamptz IS NULL
    OR created_at < $3
  )
ORDER BY created_at DESC
LIMIT $2
`

type ListNotificationsByCursorParams struct {
	TargetRole string       `json:"target_role"`
	Limit      int32        `json:"limit"`
	Cursor     sql.NullTime `json:"cursor"`
}

func (q *Queries) ListNotificationsByCursor(ctx context.Context, arg ListNotificationsByCursorParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsByCursor, arg.TargetRole, arg.Limit, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.Severity,
			&i.TargetRole,
			&i.Metadata,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET
  read = TRUE
WHERE
  target_role = $1
  AND read = FALSE
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, targetRole string) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsRead, targetRole)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications
SET
  read = TRUE
WHERE
  id = $1
`

func (q *Queries) MarkNotificationRead(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markNotificationRead, id)
	return err
}
