// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateClient(ctx context.Context, arg CreateClientParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteClient(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetClientByID(ctx context.Context, id uuid.UUID) (Client, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListClients(ctx context.Context) ([]Client, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
