{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak-admin
  labels:
    {{- include "moh-sso.labels" . | nindent 4 }}
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: {{ .Values.keycloak.admin.username | quote }}
  KC_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.keycloak.admin.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak-db
  labels:
    {{- include "moh-sso.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgresKeycloak.auth.db | quote }}
  POSTGRES_USER: {{ .Values.postgresKeycloak.auth.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresKeycloak.auth.password | quote }}
{{- end }}
