version: "3.9"

services:
  # -----------------------------
  # Keycloak Authentication Server (SSL Configured)
  # -----------------------------
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
    environment:
      KC_DB: postgres
      KC_HOSTNAME: http://localhost:8081
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8081:8080"
    depends_on:
      - keycloak-db
    networks:
      - sso_network

  # -----------------------------
  # Keycloak Database (PostgreSQL)
  # -----------------------------
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    networks:
      - sso_network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  # -----------------------------
  # Go Backend Service (Dev)
  # -----------------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: sso-backend
    environment:
      - PORT=9000
      - KEYCLOAK_URL=http://localhost:8081
      - KEYCLOAK_REALM=moh-realm
      - KEYCLOAK_CLIENT_ID=dashboard
      - KEYCLOAK_REDIRECT_URI=http://localhost:9000/api/v1/auth/callback
      - KEYCLOAK_CLIENT_SECRET=U2FsdGVkX19T2cV2PfUkkEIwdGnJICQXma6zEe+yTig=
      - DB_HOST=backend-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=sso_dashboard
    depends_on:
      - keycloak
      - backend-db
    ports:
      - "9000:9000"
    networks:
      - sso_network
    volumes:
      - ./backend:/app
    command: sh -c "go run ./cmd/server"

  # -----------------------------
  # Backend Database (Dev)
  # -----------------------------
  backend-db:
    image: postgres:15
    container_name: backend-db
    environment:
      POSTGRES_DB: sso_dashboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - backend_data:/var/lib/postgresql/data
    networks:
      - sso_network

  # -----------------------------
  # React Frontend (Dev)
  # -----------------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: sso-frontend
    environment:
      - VITE_API_URL=http://localhost:9000
      - VITE_KEYCLOAK_URL=http://localhost:8081
      - VITE_KEYCLOAK_REALM=moh-realm
      - VITE_KEYCLOAK_CLIENT_ID=dashboard
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - keycloak
    networks:
      - sso_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

# -----------------------------
# Persistent Volumes
# -----------------------------
volumes:
  keycloak_data:
  backend_data:

# -----------------------------
# Network
# -----------------------------
networks:
  sso_network:
    driver: bridge
