global:
  namespace: sso-dev

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  className: nginx
  host: sso.local
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
  tls:
    enabled: false
    secretName: ""

api:
  enabled: true
  image:
    repository: moh-sso/sso-api
    tag: dev
    pullPolicy: IfNotPresent
  replicas: 2
  service:
    port: 9000
  env:
    PORT: "9000"
    KEYCLOAK_BASE_URL: "http://{{ .Release.Name }}-keycloak:8080"
    ALLOWED_ORIGINS: "http://sso.local"
  secrets:
    JWT_SECRET: "change_me_jwt_secret"
    DB_DSN: "postgres://sso_user:change_me_app_db_password@{{ .Release.Name }}-postgres-app:5432/sso?sslmode=disable"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  probes:
    readinessPath: /ready
    livenessPath: /health
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 8
    targetCPUUtilizationPercentage: 70
  pdb:
    enabled: true
    minAvailable: 1

frontend:
  enabled: true
  image:
    repository: moh-sso/sso-frontend
    tag: dev
    pullPolicy: IfNotPresent
  replicas: 2
  service:
    port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
  pdb:
    enabled: true
    minAvailable: 1

postgresApp:
  enabled: true
  image:
    repository: postgres
    tag: 16-alpine
  persistence:
    enabled: true
    size: 10Gi
    accessModes: ["ReadWriteOnce"]
  auth:
    db: sso
    user: sso_user
    password: change_me_app_db_password
  service:
    port: 5432

postgresKeycloak:
  enabled: true
  image:
    repository: postgres
    tag: 16-alpine
  persistence:
    enabled: true
    size: 10Gi
    accessModes: ["ReadWriteOnce"]
  auth:
    db: keycloak
    user: keycloak_user
    password: change_me_keycloak_db_password
  service:
    port: 5432

keycloak:
  enabled: true
  image:
    repository: quay.io/keycloak/keycloak
    tag: 26.0.6
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    port: 8080
  admin:
    username: admin
    password: change_me_keycloak_admin_password
  config:
    KC_DB: postgres
    KC_DB_URL_HOST: "{{ .Release.Name }}-postgres-keycloak"
    KC_DB_URL_DATABASE: keycloak
    KC_HTTP_ENABLED: "true"
    KC_PROXY: edge
    KC_HOSTNAME_STRICT: "false"
    KC_HOSTNAME_STRICT_HTTPS: "false"
    KC_LOG_LEVEL: INFO
